# Generated by Django 5.1.4 on 2025-01-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_brands_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands_images', verbose_name='Изображение'),
        ),
    ]
