# Generated by Django 4.2.7 on 2025-01-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_gallery_image_alter_gallery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
