# Generated by Django 4.2.7 on 2025-01-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_subcategories_name_alter_subcategories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
