# Generated by Django 4.2.7 on 2025-01-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_subcategories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
