# Generated by Django 4.2.7 on 2025-01-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_subcategories_name_alter_subcategories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
