# Generated by Django 4.2.7 on 2025-01-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_subcategories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='subcategories_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
