# Generated by Django 4.2.7 on 2025-08-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='specifications',
            field=models.JSONField(blank=True, null=True, verbose_name='Характеристики'),
        ),
    ]
