# Generated by Django 4.2.7 on 2025-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_alter_products_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4, verbose_name='Скидка в %'),
        ),
    ]
