# Generated by Django 4.2.7 on 2025-08-17 12:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_alter_products_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Описание'),
        ),
    ]
