# Generated by Django 4.2.7 on 2025-08-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата добавления'),
        ),
    ]
