# Generated by Django 4.2.7 on 2025-08-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_products_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
