# Generated by Django 5.2.5 on 2025-09-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_alter_products_created_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
