# Generated by Django 4.2.7 on 2025-07-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость доставки')),
            ],
        ),
    ]
