# Generated by Django 4.2.7 on 2025-07-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_delivery_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Способ доставки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость доставки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна ли доставка')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='requires_delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryPrice',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliverymethod', verbose_name='Способ доставки'),
        ),
    ]
