# Generated by Django 4.2.7 on 2025-07-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliverymethod_remove_order_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Стоимость доставки'),
        ),
    ]
