# Generated by Django 4.2.7 on 2025-07-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_deliverymethod_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступна ли опция'),
        ),
    ]
