# Generated by Django 4.2.7 on 2025-07-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_deliverymethod_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='required_address',
            field=models.BooleanField(default=False, verbose_name='Требуется адрес доставки'),
        ),
    ]
